// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pajepyomtenbnttzahsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhamVweW9tdGVuYm50dHphaHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxOTg5MDUsImV4cCI6MjA3ODc3NDkwNX0.4e6B6bhlRXJXeKZy2W2AvL1qBTos25UQvEP1BojMknU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});